# Generated by Django 3.1.2 on 2020-11-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_population', models.IntegerField()),
                ('city_language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hp_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hp_latitude', models.IntegerField(blank=True, null=True)),
                ('hp_longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lf_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lf_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rp_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rp_latitude', models.IntegerField(blank=True, null=True)),
                ('rp_longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TourismPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tp_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tp_latitude', models.IntegerField(blank=True, null=True)),
                ('tp_longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='population',
            new_name='state_population',
        ),
        migrations.CreateModel(
            name='TourismPlaceFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourism_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.tourismplace')),
            ],
        ),
        migrations.CreateModel(
            name='SouvenirFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souvenir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.souvenir')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousPlaceFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='LocalFoodFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.localfood')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPlacesFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.historicalplace')),
            ],
        ),
        migrations.CreateModel(
            name='CityFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.city')),
            ],
        ),
    ]
